app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

delete_basket:
    path:     /usun
    defaults: { _controller: AppBundle:Default:deleteBasket}