AppBundle\Entity\Log:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        prodName:
            type: string
            length: 255
        date:
            type: datetime
    lifecycleCallbacks: {  }
